"""Type stubs for the `a` extension module."""
import asyncio
from collections.abc import Callable

class Frame:
    """Immutable zero-copy frame snapshot (supports the buffer protocol;
    non-contiguous — padded row stride)."""

    @property
    def shape(self) -> tuple[int, int, int]: ...
    @property
    def strides(self) -> tuple[int, int, int]: ...
    def _data_ptr(self) -> int: ...

class FrameStream:
    """Async iterator over a subscription: `async for frame in src.frames()`.

    Bounded queue with drop-oldest; teardown is the caller's
    (`src.unsubscribe(stream.id)`), as with any subscription."""

    @property
    def id(self) -> int: ...
    @property
    def dropped(self) -> int: ...
    @property
    def pending(self) -> int: ...
    def __aiter__(self) -> FrameStream: ...
    def __anext__(self) -> asyncio.Future[Frame]: ...

class A:
    def __init__(self, id: int) -> None: ...
    @property
    def id(self) -> int: ...
    @property
    def counter(self) -> int: ...
    @property
    def scale(self) -> float: ...
    def increment(self) -> None: ...
    def fill(self, seed: int) -> None: ...
    def frame(self) -> Frame: ...
    def subscribe(self, cb: Callable[[Frame], object]) -> int: ...
    def frames(self, capacity: int = 4) -> FrameStream: ...
    def unsubscribe(self, id: int) -> None: ...
    def stream(self, count: int, period_ms: int) -> None: ...
    def stream_join(self) -> None: ...
    def capture(self) -> asyncio.Future[Frame]: ...
    def _data_ptr(self) -> int: ...
    def _test_call_while_borrowed(self, cb: Callable[[], object]) -> None:
        """Test hook: run `cb` while this object is exclusively borrowed, so a
        re-entrant unwrap through the capsule must be refused."""

_C_API: object
