"""Type stubs for the `b` extension module."""
import asyncio
from a import A, Frame

def process(obj: A) -> int: ...
def checksum(obj: A) -> int: ...
def process_fast(obj: A) -> float: ...
def grab_frame(obj: A) -> Frame: ...
def capture_checksum(obj: A) -> asyncio.Future[int]: ...
def _test_panic_in_with_a(obj: A) -> int:
    """Test hook: panic inside the capsule callback. The unwind crosses two
    extern "C" frames and must arrive as a Python exception, not an abort."""
